### ISSUE TITLE
Microsoft Edge support

### ISSUE THREAD

**Issue by imasaru** [naei/wanikani-companion#10]
I was able to use the Edge Extension Toolkit to convert `wanikani-companion`, and basic functions work. In-App browsing doesn't work (eternal loop), and the toolbar icon doesn't show. I will try to get this to full functionality, but I don't have a lot of time on my hands right now...

All this work is on the `edge` branch of my fork.

**Comment by naei** [comment]
This project is for the Chrome browser only and I don't plan to support Microsoft Edge.
If you want to provide a Edge version this is great and feel free to work on it :+1:
