### ISSUE TITLE
[Feature Request]  3 second block after getting it wrong

### ISSUE THREAD

**Issue by worthy7** [naei/wanikani-companion#16]
Hi there,

I have an extremely bad habit of pressing enter twice after entering my answers, which means I skip reading the correct answer in the info section.

I can't be the only one, so I propose a simple solution to just block the second Enter key press/button push when the answer was incorrect.

1) Options menu has a check to enable the feature "Incorrect answer blocks progress for 3 seconds"
2) When an answer is incorrect, simply block the continue button (the arrow next to the answer input?)

**Comment by naei** [comment]
Hello @worthy7, thank you for your message. 
This feature is directly related to WaniKani, and it may have been designed that way for a reason, therefore, there are no plans to implement anything in this extension that would change the way Wanikani works.
However, you can address this request directly to the WaniKani team!
