### ISSUE TITLE
Can't see reviews, X-Frame-Options: SAMEORIGIN issue

### ISSUE THREAD

**Issue by grahas** [naei/wanikani-companion#18]
<img width="368" alt="Screen Shot 2021-07-02 at 12 16 13 AM" src="https://user-images.githubusercontent.com/8950797/124229366-b92e4b80-daca-11eb-8468-ca1f7760012c.png">

Chrome console is _Refused to display 'https://www.wanikani.com/' in a frame because it set 'X-Frame-Options' to 'sameorigin'._

I get this when I click reviews

**Comment by naei** [comment]
Hi @grahas, I do not have any issue when clicking on "lessons" or "reviews". Could you give me the steps to reproduce it please?

**Comment by grahas** [comment]
Hi thanks for the response. I attached a video. https://youtu.be/quSagpSyggk

**Comment by naei** [comment]
Thank you for reporting this issue @grahas. It should be fixed by now and the update will be published on the Chrome Web Store soon. Do not hesitate to confirm.

**Comment by grahas** [comment]
Ok looks like it is fixed now!
