### ISSUE TITLE
Add when is the next review, etc.?

### ISSUE THREAD

**Issue by agarny** [naei/wanikani-companion#2]
I have been using your extension for a few days and I am finding it to be very useful (so thanks a lot for it indeed!).

However, there is something that I wish was present, namely some information on when the next review is, as well as how many of them there are going to be in the next hour and the next day. In other words, the information we can see when looking up our dashboard.

**Comment by naei** [comment]
Hello agarny, thank you for your message. 

I have not planned to add these information at the moment, but I will think about it. Do not hesitate to contribute to this project and add some nice features! ;)
