### ISSUE TITLE
Number of lessons/reviews doesn't update automatically

### ISSUE THREAD

**Issue by seanblue** [naei/wanikani-companion#6]
Even when the refresh interval is short, the badge does not update automatically when more lessons/reviews are ready.

**Comment by naei** [comment]
Some people experienced this issue but I was never able to reproduce it.
Could you tell me your OS and Chrome version, and also if you put (manually or automatically) your computer into sleep mode before you noticed this bug please?

**Comment by seanblue** [comment]
I am using Windows 10 and Chrome 54.0.2840.99. I always have my computer in sleep mode and when I wake it up I go to an already-open instance of Chrome.

**Comment by seanblue** [comment]
After restarting Chrome, the badge updates as expected and notifications now show up. I put my computer to sleep for a minute, but the next notification still showed up correctly. I'll update you in a couple days if the issue starts happening again.

**Comment by naei** [comment]
Ok thank you for your feedback.

**Comment by seanblue** [comment]
The issue showed up again after a long period of sleeping (much longer that the refresh period I had set). It does seem to have something to do with the refresh period passing when the computer is asleep.

**Comment by naei** [comment]
Thanks for havng t

**Comment by naei** [comment]
Thanks @seanblue. I'll try to handle the refresh interval when the browser is idle.
